<a href="https://colab.research.google.com/github/surajsarkar3526-cyber/MachineLearning/blob/main/Encoding_In_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is Encoding in Machine Learning
Encoding in ML is the process of converting categorical data into numerical format so that algorithms can process it.

After

Ordinal Encoding:-

Ordinal encoding respects order in categories. For example, education levels have a natural order:

Highschool < Graduate < Postgrad

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/binary_classification_sample.csv')

In [3]:
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,HR,Bachelors,67.964728,0
1,69,31258.344158,16,Female,Engineering,High School,21.825389,0
2,46,79176.734217,4,Male,HR,PhD,94.996118,0
3,32,47699.953137,4,Male,Engineering,High School,78.634501,1
4,60,36395.191619,5,Male,Marketing,High School,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,Female,Engineering,Bachelors,77.985099,1
196,30,49573.678136,14,Female,Marketing,Bachelors,3.961883,1
197,58,24253.633311,27,Female,HR,High School,48.050695,0
198,20,NaN,12,Female,Sales,High School,NaN,0
199,56,69897.075025,17,Male,Marketing,Bachelors,24.204502,0

In [6]:
df.shape

(169, 8)

###How to Apply Oridinal Encoding?

In [4]:
df.dropna(inplace=True)

In [5]:
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,HR,Bachelors,67.964728,0
1,69,31258.344158,16,Female,Engineering,High School,21.825389,0
2,46,79176.734217,4,Male,HR,PhD,94.996118,0
3,32,47699.953137,4,Male,Engineering,High School,78.634501,1
4,60,36395.191619,5,Male,Marketing,High School,8.941100,1
...,...,...,...,...,...,...,...,...
194,44,33125.723933,13,Male,Sales,PhD,86.012240,1
195,69,69228.805705,10,Female,Engineering,Bachelors,77.985099,1
196,30,49573.678136,14,Female,Marketing,Bachelors,3.961883,1
197,58,24253.633311,27,Female,HR,High School,48.050695,0
199,56,69897.075025,17,Male,Marketing,Bachelors,24.204502,0

In [7]:
df.shape

(169, 8)

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
ord_encoder = OrdinalEncoder
ord_encoder = OrdinalEncoder()
df['Education'] = ord_encoder.fit_transform(df[['Education']]).astype(int)
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,HR,0,67.964728,0
1,69,31258.344158,16,Female,Engineering,1,21.825389,0
2,46,79176.734217,4,Male,HR,3,94.996118,0
3,32,47699.953137,4,Male,Engineering,1,78.634501,1
4,60,36395.191619,5,Male,Marketing,1,8.941100,1
...,...,...,...,...,...,...,...,...
194,44,33125.723933,13,Male,Sales,3,86.012240,1
195,69,69228.805705,10,Female,Engineering,0,77.985099,1
196,30,49573.678136,14,Female,Marketing,0,3.961883,1
197,58,24253.633311,27,Female,HR,1,48.050695,0
199,56,69897.075025,17,Male,Marketing,0,24.204502,0

In [18]:
df['Department'] = ord_encoder.fit_transform(df[['Department']]).astype(int)
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,1,0,67.964728,0
1,69,31258.344158,16,Female,0,1,21.825389,0
2,46,79176.734217,4,Male,1,3,94.996118,0
3,32,47699.953137,4,Male,0,1,78.634501,1
4,60,36395.191619,5,Male,2,1,8.941100,1
...,...,...,...,...,...,...,...,...
194,44,33125.723933,13,Male,3,3,86.012240,1
195,69,69228.805705,10,Female,0,0,77.985099,1
196,30,49573.678136,14,Female,2,0,3.961883,1
197,58,24253.633311,27,Female,1,1,48.050695,0
199,56,69897.075025,17,Male,2,0,24.204502,0