<a href="https://colab.research.google.com/github/surajsarkar3526-cyber/MachineLearning/blob/main/Filling_Missing_Values%2C_SimpleImputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Filling Missing Values, SimpleImputer

##Load Dataset

In [2]:
import pandas as pd
df = pd.read_csv("binary_classification_sample.csv")
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,HR,Bachelors,67.964728,0
1,69,31258.344158,16,Female,Engineering,High School,21.825389,0
2,46,79176.734217,4,Male,HR,PhD,94.996118,0
3,32,47699.953137,4,Male,Engineering,High School,78.634501,1
4,60,36395.191619,5,Male,Marketing,High School,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,Female,Engineering,Bachelors,77.985099,1
196,30,49573.678136,14,Female,Marketing,Bachelors,3.961883,1
197,58,24253.633311,27,Female,HR,High School,48.050695,0
198,20,NaN,12,Female,Sales,High School,NaN,0
199,56,69897.075025,17,Male,Marketing,Bachelors,24.204502,0

##Filling Missing Values

In [3]:
df.isnull().sum()

Age               0
Salary           15
Experience        0
Gender            0
Department        0
Education        10
LocationScore    10
Purchased         0
dtype: int64

In [4]:
from sklearn.impute import SimpleImputer

In [5]:
# fill numerical column values
impt1 = SimpleImputer(strategy='mean')
df[['Salary','LocationScore']] = impt1.fit_transform(df[['Salary','LocationScore']])

In [6]:
df.isnull().sum()

Age               0
Salary            0
Experience        0
Gender            0
Department        0
Education        10
LocationScore     0
Purchased         0
dtype: int64

In [7]:
impt2 = SimpleImputer(strategy='most_frequent')

df[['Education']] = impt2.fit_transform(df[['Education']])

In [8]:
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,HR,Bachelors,67.964728,0
1,69,31258.344158,16,Female,Engineering,High School,21.825389,0
2,46,79176.734217,4,Male,HR,PhD,94.996118,0
3,32,47699.953137,4,Male,Engineering,High School,78.634501,1
4,60,36395.191619,5,Male,Marketing,High School,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,Female,Engineering,Bachelors,77.985099,1
196,30,49573.678136,14,Female,Marketing,Bachelors,3.961883,1
197,58,24253.633311,27,Female,HR,High School,48.050695,0
198,20,49864.421754,12,Female,Sales,High School,52.638377,0
199,56,69897.075025,17,Male,Marketing,Bachelors,24.204502,0

In [9]:
df.isnull().sum()

Age              0
Salary           0
Experience       0
Gender           0
Department       0
Education        0
LocationScore    0
Purchased        0
dtype: int64