<a href="https://colab.research.google.com/github/surajsarkar3526-cyber/MachineLearning/blob/main/ML_Day_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Here:

X is our input features

y is the output or labels

test_size=0.2 means 20% of the data will be used for testing

random_state=42 just helps to make the results reproducible

After this, you get 4 things:

X_train, y_train: for training

X_test, y_test: for testing

In [1]:
# train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

What is Encoding in Scikit-learn?
Encoding is the process of converting categorical (non-numeric) data into a numeric format so that machine learning models can process it.

image.png

In scikit-learn, one common method is:

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/binary_classification_sample.csv')
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,Female,HR,Bachelors,67.964728,0
1,69,31258.344158,16,Female,Engineering,High School,21.825389,0
2,46,79176.734217,4,Male,HR,PhD,94.996118,0
3,32,47699.953137,4,Male,Engineering,High School,78.634501,1
4,60,36395.191619,5,Male,Marketing,High School,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,Female,Engineering,Bachelors,77.985099,1
196,30,49573.678136,14,Female,Marketing,Bachelors,3.961883,1
197,58,24253.633311,27,Female,HR,High School,48.050695,0
198,20,NaN,12,Female,Sales,High School,NaN,0
199,56,69897.075025,17,Male,Marketing,Bachelors,24.204502,0

###How to Apply Label Encoding?

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Gender'] = encoder.fit_transform(df['Gender'])
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,0,HR,Bachelors,67.964728,0
1,69,31258.344158,16,0,Engineering,High School,21.825389,0
2,46,79176.734217,4,1,HR,PhD,94.996118,0
3,32,47699.953137,4,1,Engineering,High School,78.634501,1
4,60,36395.191619,5,1,Marketing,High School,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,0,Engineering,Bachelors,77.985099,1
196,30,49573.678136,14,0,Marketing,Bachelors,3.961883,1
197,58,24253.633311,27,0,HR,High School,48.050695,0
198,20,NaN,12,0,Sales,High School,NaN,0
199,56,69897.075025,17,1,Marketing,Bachelors,24.204502,0

In [9]:
df['Department'].value_counts()

Department
Sales          58
HR             50
Engineering    47
Marketing      45
Name: count, dtype: int64

In [10]:
df['Department'] = encoder.fit_transform(df['Department'])
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,0,1,Bachelors,67.964728,0
1,69,31258.344158,16,0,0,High School,21.825389,0
2,46,79176.734217,4,1,1,PhD,94.996118,0
3,32,47699.953137,4,1,0,High School,78.634501,1
4,60,36395.191619,5,1,2,High School,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,0,0,Bachelors,77.985099,1
196,30,49573.678136,14,0,2,Bachelors,3.961883,1
197,58,24253.633311,27,0,1,High School,48.050695,0
198,20,NaN,12,0,3,High School,NaN,0
199,56,69897.075025,17,1,2,Bachelors,24.204502,0

In [11]:
df['Department'].value_counts()

Department
3    58
1    50
0    47
2    45
Name: count, dtype: int64

In [12]:
df['Education'].value_counts()

Education
Bachelors      51
Masters        50
High School    46
PhD            43
Name: count, dtype: int64

In [16]:
df['Education'] = encoder.fit_transform(df['Education'])

In [17]:
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,0,1,0,67.964728,0
1,69,31258.344158,16,0,0,1,21.825389,0
2,46,79176.734217,4,1,1,3,94.996118,0
3,32,47699.953137,4,1,0,1,78.634501,1
4,60,36395.191619,5,1,2,1,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,0,0,0,77.985099,1
196,30,49573.678136,14,0,2,0,3.961883,1
197,58,24253.633311,27,0,1,1,48.050695,0
198,20,NaN,12,0,3,1,NaN,0
199,56,69897.075025,17,1,2,0,24.204502,0

In [18]:
df['Education'].value_counts()

Education
0    51
2    50
1    46
3    43
4    10
Name: count, dtype: int64

In [19]:
df

,Age,Salary,Experience,Gender,Department,Education,LocationScore,Purchased
0,56,51905.183591,27,0,1,0,67.964728,0
1,69,31258.344158,16,0,0,1,21.825389,0
2,46,79176.734217,4,1,1,3,94.996118,0
3,32,47699.953137,4,1,0,1,78.634501,1
4,60,36395.191619,5,1,2,1,8.941100,1
...,...,...,...,...,...,...,...,...
195,69,69228.805705,10,0,0,0,77.985099,1
196,30,49573.678136,14,0,2,0,3.961883,1
197,58,24253.633311,27,0,1,1,48.050695,0
198,20,NaN,12,0,3,1,NaN,0
199,56,69897.075025,17,1,2,0,24.204502,0